# -*- coding: utf-8 -*-
"""Textclassifier

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Nm7F0TbLxAx38TyHFIpGO3f46I987dJ
"""

from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

"""# Define the training data

"""

train_data = pd.DataFrame({
    'doc': [1, 2, 3, 4, 5, 6, 7],
    'words': ['W1 W2 W3 W4 W5', 'W1 W1 W4 W3', 'W1 W2 W5', 'W5 W6 W1 W2 W3', 'W4 W5 W6', 'W4 W6 W3', 'W2 W2 W4 W3 W5 W5'],
    'author': ['C', 'C', 'C', 'W', 'W', 'F', 'F']
})

"""# Define the test data

"""

test_data = pd.DataFrame({
    'doc': [8],
    'words': ['W1 W4 W6 W5 W3']
})

"""# Define the vectorizer

"""

vectorizer = CountVectorizer()

"""# Transform the training data

"""

X_train = vectorizer.fit_transform(train_data['words'])
y_train = train_data['author']

"""# Train the classifier

"""

clf = MultinomialNB()
clf.fit(X_train, y_train)

"""# Transform the test data

"""

X_test = vectorizer.transform(test_data['words'])

"""# Predict the author of the test document

"""

predicted_author = clf.predict(X_test)[0]

print('The predicted author of Hamlet is:', predicted_author)